### ISSUE TITLE
Extienda y modifique el analizador para que acepte el lenguaje descrito por la gramática

### ISSUE THREAD

**Issue by KevinRM** [KevinRM/pl_practica_4#1]

**Comment by KevinRM** [comment]
Añadi lo que hay aqui http://crguezl.github.io/pl-html/node26.html.
Falta Añada al lenguaje la sentencia "if" condition "then" statement "else" statement.
Comprueba si esta bien por si me comi algo

**Comment by SCeruso** [comment]
Listo, tambien suma y resta
